---
- name: Add Jenkins repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Configure Jenkins systemd service
  template:
    src: jenkins.conf.j2
    dest: /etc/systemd/system/jenkins.service.d/override.conf
  notify: Restart Jenkins

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
