---
- name: Install Amazon Corretto 17 (Java 17 for Amazon Linux)
  yum:
    name: java-17-amazon-corretto-devel
    state: present

- name: Set JAVA_HOME environment variable
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto"'
    state: present
    create: yes

- name: Make JAVA_HOME available for current session
  shell: |
    export JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto"
    export PATH=$PATH:$JAVA_HOME/bin
  args:
    executable: /bin/bash