plugin: aws_ec2
regions:
  - us-east-1  # Replace with your AWS region
filters:
  tag:Application: jenkins
  instance-state-name: running

keyed_groups:
  - key: tags.Role
    prefix: role_
  - key: tags.Environment
    prefix: env_

compose:
  ansible_host: public_ip_address