---
# Jenkins configuration
jenkins_home: /var/lib/jenkins
jenkins_admin_username: admin
jenkins_admin_password: !vault |
  $ANSIBLE_VAULT_PASSWORD_PLACEHOLDER

# Jenkins plugin list
jenkins_plugins:
  - git
  - github
  - workflow-aggregator
  - credentials
  - authorize-project
  - matrix-auth
  - pipeline-stage-view