---
- hosts: all
  become: yes
  roles:
    - common

- hosts: role_jenkins_master
  become: yes
  roles:
    - jenkins

- hosts: role_jenkins_slave
  become: yes
  roles:
    - jenkins

- hosts: role_sonarqube
  become: yes
  roles:
    - sonarqube