---
- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'